[project]
name = "kl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy==1.26.4",
    "tensorboard>=2.19.0",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "torch>=2.6.0",
]
